apiVersion: v1
kind: Service
metadata:
  name: eshop
  labels:
    app: eshop
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: eshop
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: inventory
---
apiVersion: v1
kind: Service
metadata:
  name: billing
  labels:
    app: billing
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: billing
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: delivery
---
apiVersion: v1
kind: Service
metadata:
  name: logistics
  labels:
    app: logistics
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: logistics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
        - name: eshop
          image: zhaohuabing/liveproject-tracing:v4.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: zhaohuabing/liveproject-tracing:v4.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: zhaohuabing/liveproject-tracing:v4.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: zhaohuabing/liveproject-tracing:v4.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistics
  template:
    metadata:
      labels:
        app: logistics
    spec:
      containers:
        - name: logistics
          image: zhaohuabing/liveproject-tracing:v4.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

